User.create!([
  {email: "user@test.com", encrypted_password: "$2a$10$HIPuB47xw4g484rRbQ.yI.NIiS.s80kX2VmKt.mRLhT5iAKjD/YmS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-12-05 06:46:33", last_sign_in_at: "2015-12-05 03:37:17", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: nil, admin: false},
  {email: "al@ilseman.com", encrypted_password: "$2a$10$v9k4ajVAL0Ux4CerMR74Oup6iqcDV./sZdx9LGLl2EjPy4UtUlJY.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2015-12-06 06:05:03", last_sign_in_at: "2015-12-06 01:11:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: nil, admin: true}
])
Post.create!([
  {title: "What I need for a poster", body: "This is cute and all, but I don't want to just post things in one shot... That is crazy.\r\nI need a 'published' attribute in my db.\r\nThis attribute will act like the admin attribute does for users. It is a bool and it defaults to false. This form and route can stay exactly how it is except for a redirect to the admin page. On the admin page there will be a list of drafts for editing or publishing... Ooooh. How fun!\r\n\r\n\r\nThe other thing I need is some way to account for formatting in my posting. I am thinking I want this here to be in html? I would love to have a JS html editor. I don't consider this cheating since I am making the whole application anyway. One such thing must exist right? I'm going looking.\r\n\r\nMaybe better yet, something that accepts markdown. The possibilities are endless, so I had better focus on getting an actual blog ONLINE first.", author: nil, published: false},
  {title: "My sweet Ipsum", body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\ntempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\nquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\nconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\ncillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\nproident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\ntempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\nquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\nconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\ncillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\nproident, sunt in culpa qui officia deserunt mollit anim id est laborum.", author: nil, published: false},
  {title: "Building a blog site is fun", body: "This is a challenge for sure, but I am learning so much about all of the rails helpers and how to make best use of them. It seems that all things are possible with the help of the api docs, although sometimes it can get a bit rough. For instance, I still have not figured out how to wrap something like an icon in a link of a specific class when that link needs to be called with its helper. I may have to resort to writing my own method in that case which isn't hard, that's just not where my head was at when I was trying originally.", author: nil, published: false},
  {title: "How do I get some HTML posts?", body: "This is fun, and the website looks good. But how do I get my posts to look good? Markdown? I know there are many solutions, I just don't know what they are. render html? ", author: nil, published: false}
])
